name: "Install Yotta"
description: "Install Yotta"
runs:
  using: "composite"
  steps:
    - name: "Update apt-get"
      run: "sudo apt-get update"
      shell: "bash"
    - name: "Install dependencies"
      run: "sudo apt-get install -y cmake build-essential libffi-dev libssl-dev unzip wget"
      shell: "bash"
    - name: "Install Ninja"
      run: |
        wget -q https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip &&
        unzip ninja-linux.zip &&
        sudo mv ninja /usr/local/bin/ninja &&
        sudo chmod +x /usr/local/bin/ninja &&
        ninja --version &&
        sudo ln -s /usr/bin/ninja /usr/bin/ninja-build
      shell: "bash"
    - name: "Install ARM embedded toolchain"
      shell: "bash"
      run: |
        wget -q https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 &&
        sudo tar xjf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 -C /usr/share/ &&
        sudo ln -s /usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gcc /usr/bin/arm-none-eabi-gcc &&
        sudo ln -s /usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-g++ /usr/bin/arm-none-eabi-g++ &&
        sudo ln -s /usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gdb /usr/bin/arm-none-eabi-gdb &&
        sudo ln -s /usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-size /usr/bin/arm-none-eabi-size
    - name: "Show versions of ARM embedded toolchain"
      shell: "bash"
      run: |
        arm-none-eabi-gcc --version &&
        arm-none-eabi-g++ --version &&
        arm-none-eabi-gdb --version &&
        arm-none-eabi-size --version
    - name: "Install Python 2.7"
      run: "sudo apt-get install -y python2 python2-dev"
      shell: "bash"
    - name: "Install Yotta"
      run: "pip install yotta"
      shell: "bash"
    - name: "Add to path"
      shell: "bash"
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: "Run 'yotta clean'"
      shell: "bash"
      run: "yotta clean"