name: "Install Yotta"
description: "Install Yotta"
runs:
  using: "composite"
  steps:
    - name: "Update apt-get"
      run: "sudo apt-get update"
      shell: "bash"
    - name: "Install dependencies"
      run: "sudo apt-get install -y cmake build-essential libffi-dev libssl-dev unzip wget"
      shell: "bash"
    - name: "Install Ninja"
      run: |
        wget https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip &&
        unzip ninja-linux.zip &&
        mv ninja /usr/local/bin/ninja &&
        chmod +x /usr/local/bin/ninja
      shell: "Bash"
    - name: "Install Python 2.7"
      run: "sudo apt-get install -y python2 python2-dev"
      shell: "bash"
    - name: "Install Yotta"
      run: "pip install yotta"
      shell: "bash"
    - name: "Add to path"
      shell: "bash"
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH