name: "Install Yotta"
description: "Install Yotta"
runs:
  using: "composite"
  steps:
    - name: "Install dependencies"
      run: "sudo apt-get install -y cmake --quiet"
      shell: "bash"
    - name: "Install Ninja"
      run: |
        wget -q https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip &&
        unzip ninja-linux.zip &&
        sudo mv ninja /usr/local/bin/ninja &&
        sudo chmod +x /usr/local/bin/ninja &&
        sudo ln -s /usr/bin/ninja /usr/bin/ninja-build &&
        sudo ln -s /usr/bin/ninja /usr/local/bin/Ninja
      shell: "bash"
    - name: "Install Python 2.7"
      run: "sudo apt-get install -y python2 python2-dev --quiet"
      shell: "bash"
    - name: "Add to path"
      shell: "bash"
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: "Install Yotta"
      run: "pip install yotta --quiet"
      shell: "bash"
    - name: "Run 'yotta clean'"
      shell: "bash"
      run: "yotta clean"