name: "Install Yotta"
description: "Install Yotta"
runs:
  steps:
    - uses: "seanmiddleditch/gha-setup-ninja@master"
    - uses: "actions/setup-python@v2"
      with:
        python-version: '2.7.x'
    - run: "pip install yotta"
