name: "Install Yotta"
description: "Install Yotta"
runs:
  using: "composite"
  steps:
    - name: "Update apt-get"
      run: "sudo apt-get update"
      shell: "bash"
    - name: "Install dependencies"
      run: "sudo apt-get install -y cmake build-essential ninja-build libffi-dev libssl-dev"
      shell: "bash"
    - name: "Install Python 2.7"
      run: "sudo apt-get install -y python2 python2-dev"
      shell: "bash"
    - name: "Install Yotta"
      run: "pip install yotta"
      shell: "bash"
    - name: "Add to path"
      run: "echo "$HOME/.local/bin" >> $GITHUB_PATH"
      shell: "bash"
